permalink: pretty
markdown: kramdown
highlighter: rouge
liquid:
  error_mode: lax

title: site title
desc: site description
keywords: site, keywords
image: "/assets/img/berkeley-indian-rock.jpg"

# owner
author:
  name: your name
  email: your@email.com

# site data
collections:
  post: { output: true }
  project: { output: true }
